AWSTemplateFormatVersion: "2010-09-09"
Description: IAM Roles for AI Stock Trading Agent

Resources:
  # IAM Role for Lambda (Data Collection)
  AiStockTradingLambdaRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # IAM Role for SageMaker (Model Training and Prediction)
  AiStockTradingSageMakerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "sagemaker.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSageMakerFullAccess

  # IAM Role for API Gateway (Trade Execution)
  AiStockTradingApiGatewayRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonAPIGatewayInvokeFullAccess

  # IAM Role for CloudWatch (Monitoring)
  AiStockTradingCloudWatchRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cloudwatch.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess

  # IAM Role for CloudFormation Read-Only Access
  AiStockTradingCloudFormationReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "cloudformation.amazonaws.com"
            Action: "sts:AssumeRole"
      Path: "/"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess

Outputs:
  AiStockTradingLambdaRole:
    Value: !GetAtt "AiStockTradingLambdaRole.Arn"
    Description: "IAM Role for Lambda (Data Collection)"

  AiStockTradingSageMakerRole:
    Value: !GetAtt "AiStockTradingSageMakerRole.Arn"
    Description: "IAM Role for SageMaker (Model Training)"

  AiStockTradingApiGatewayRole:
    Value: !GetAtt "AiStockTradingApiGatewayRole.Arn"
    Description: "IAM Role for API Gateway (Trade Execution)"

  AiStockTradingCloudWatchRole:
    Value: !GetAtt "AiStockTradingCloudWatchRole.Arn"
    Description: "IAM Role for CloudWatch (Monitoring)"

  AiStockTradingCloudFormationReadOnlyRole:
    Value: !GetAtt "AiStockTradingCloudFormationReadOnlyRole.Arn"
    Description: "IAM Role for CloudFormation Read-Only Access"
