AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy the AiStockTradingLambda.

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: The name of the S3 bucket containing the Lambda function code.
  LambdaCodeKey:
    Type: String
    Description: The S3 key for the Lambda function code.
  DeploymentTimestamp:
    Type: String
    Description: A dummy parameter to force updates.

Resources:
  AlphaVantageAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "AlphaVantageAPIKey"
      SecretString: '{"ALPHA_VANTAGE_API_KEY": "HMEL7GGNZDPTXC1U"}'

  AiStockTradingLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: AiStockTradingLambdaRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "lambda.amazonaws.com"
            Action: "sts:AssumeRole"
      Policies:
        - PolicyName: AiStockTradingLambdaExecutionPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "secretsmanager:GetSecretValue"
                Resource:
                  - !Ref AlphaVantageAPIKeySecret

  AiStockTradingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AiStockTradingLambda
      Runtime: python3.9
      Role: !GetAtt AiStockTradingLambdaRole.Arn
      Handler: main.lambda_handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
          ALPHA_VANTAGE_API_KEY_SECRET: !Ref AlphaVantageAPIKeySecret
  AiStockTradingLambdaPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: AiStockTradingLambdaSecretAccessPolicy
      Roles: 
        - !Ref AiStockTradingLambdaRole
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Action:
              - "secretsmanager:GetSecretValue"
            Resource:
              - !Ref AlphaVantageAPIKeySecret
Outputs:
  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref AiStockTradingLambda