Resources:
  # Create the secret in Secrets Manager
  AlphaVantageAPIKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Name: "AlphaVantageAPIKey"
      SecretString: '{"ALPHA_VANTAGE_API_KEY": "HMEL7GGNZDPTXC1U"}'

  # IAM policy allowing Lambda to read secrets
  AiStockTradingLambdaRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: LambdaSecretsManagerAccessPolicy
      Roles:
        - !Ref AiStockTradingLambdaRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - secretsmanager:GetSecretValue
            Resource: arn:aws:secretsmanager:REGION:ACCOUNT_ID:secret:AlphaVantageAPIKey-*

  AiStockTradingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AiStockTradingLambda
      Runtime: python3.9
      Role: arn:aws:iam::460888320683:role/ai-stock-trading-roles-AiStockTradingLambdaRole-vucD1NO1QfFX
      Handler: main.lambda_handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: !Ref LambdaCodeKey
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          LOG_LEVEL: INFO
          ENVIRONMENT: dev
          ALPHA_VANTAGE_API_KEY: !Ref AlphaVantageAPIKeySecret

Outputs:
  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref AiStockTradingLambda
