AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to deploy the AiStockTradingLambda.

Parameters:
  LambdaCodeBucket:
    Type: String
    Description: The name of the S3 bucket containing the Lambda function code.

Resources:
  AiStockTradingLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: AiStockTradingLambda
      Runtime: python3.9
      Role: arn:aws:iam::460888320683:role/ai-stock-trading-roles-AiStockTradingLambdaRole-34q5o8m2cFF7
      Handler: main.lambda_handler
      Code:
        S3Bucket: !Ref LambdaCodeBucket
        S3Key: code/ai_stock_trading_lambda.zip
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          LOG_LEVEL: INFO
          ENVIRONMENT: dev

Outputs:
  LambdaFunctionName:
    Description: Lambda function name
    Value: !Ref AiStockTradingLambda
