name: Delete S3 Stock Data Bucket

on:
  push:
    branches:
      - delete

jobs:
  delete:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Delete S3 Bucket CloudFormation stack
        run: |
          aws cloudformation delete-stack --stack-name stock-trading-s3-bucket-stack
