name: Deploy Infra

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Validate CloudFormation template (optional but recommended)
      - name: Validate CloudFormation template
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/infra.yaml

      # Deploy CloudFormation Stack
      - name: Deploy CloudFormation Stack
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/infra.yaml \
            --stack-name ai-stock-trading-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

      # Output the stack status (optional)
      - name: Get Stack Status
        run: |
          aws cloudformation describe-stacks \
            --stack-name ai-stock-trading-stack \
            --query 'Stacks[0].StackStatus'
