name: Deploy AiStockTradingLambda

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    environment: production

    steps:

    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies (if needed, e.g., for Lambda packaging)
    - name: Install dependencies
      run: |
        pip install -r lambda/process_raw/requirements.txt

    # Zip the Lambda function code
    - name: Zip Lambda function code
      run: |
        python -m zipfile -c ai_stock_trading_lambda.zip lambda/process_raw/.

    # Upload Lambda code to S3 with a unique key (using timestamp)
    - name: Upload Lambda code to S3
      run: |
        TIMESTAMP=$(date +%s)
        aws s3 cp ai_stock_trading_lambda.zip s3://ai-stock-trading-raw-data/code/ai_stock_trading_lambda_$TIMESTAMP.zip

    # Delete the ZIP file after upload
    - name: Delete ZIP file
      run: |
        rm ai_stock_trading_lambda.zip

    # Deploy CloudFormation Stack
    - name: Deploy CloudFormation stack
      run: |
        aws cloudformation deploy \
          --template-file cloudformation/lambda.yaml \
          --stack-name ai-stock-trading-lambda-stack \
          --parameter-overrides LambdaCodeBucket=ai-stock-trading-raw-data LambdaCodeKey=code/ai_stock_trading_lambda_$TIMESTAMP.zip \
          --no-fail-on-empty-changeset