name: Deploy AiStockTradingLambda

on:
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest
    environment: production

    steps:

    # Checkout the code from the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    # Set up Python
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    # Install dependencies into the lambda/process_raw/ directory
    - name: Install dependencies
      run: |
        pip install -r lambda/process_raw/requirements.txt -t lambda/process_raw/

    # Zip the Lambda function code and dependencies
    - name: Zip Lambda function code
      run: |
        cd lambda/process_raw/
        zip -r ai_stock_trading_lambda.zip .

    # Upload Lambda code to S3 with the same key
    - name: Upload Lambda code to S3
      run: |
        aws s3 cp lambda/process_raw/ai_stock_trading_lambda.zip s3://ai-stock-trading-raw-data/code/ai_stock_trading_lambda.zip

    # Deploy CloudFormation Stack
    - name: Deploy CloudFormation stack
      run: |
        TIMESTAMP=$(date +%s)
        aws cloudformation deploy \
          --template-file cloudformation/lambda.yaml \
          --stack-name ai-stock-trading-lambda-stack \
          --parameter-overrides LambdaCodeBucket=ai-stock-trading-raw-data LambdaCodeKey=code/ai_stock_trading_lambda.zip DeploymentTimestamp=$TIMESTAMP \
          --no-fail-on-empty-changeset