name: Deploy AWS Glue Job

on:
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  deploy-glue-job:
    runs-on: ubuntu-latest
    environment: production

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials for GitHub Actions
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Change to your desired region

      # Step 3: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 4: Install system dependencies (required for Glue job)
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake build-essential

      # Step 5: Install Python dependencies for Glue job
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r glue/process_clean/requirements.txt

      # Step 6: Zip the Glue job code and dependencies
      - name: Zip Glue job code
        run: |
          cd glue/process_clean
          zip -r glue_job_code.zip . -x "*.git*" -x "*.github*"  # Exclude unnecessary files

      # Step 7: Upload the zipped Glue job code to S3
      - name: Upload Glue job code to S3
        run: |
          aws s3 cp glue/process_clean/glue_job_code.zip s3://ai-stock-trading-raw-data/code/glue_job_code.zip

      # Step 8: Deploy CloudFormation Stack for Glue job (update or create)
      - name: Deploy CloudFormation stack
        run: |
          TIMESTAMP=$(date +%s)
          aws cloudformation deploy \
            --template-file cloudformation/process-glue.yaml \
            --stack-name ai-stock-trading-glue-job-stack \
            --parameter-overrides GlueCodeBucket=ai-stock-trading-raw-data GlueCodeKey=code/glue_job_code.zip DeploymentTimestamp=$TIMESTAMP \
            --capabilities CAPABILITY_NAMED_IAM \
            --no-fail-on-empty-changeset

